<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Chaipoints-MacBook-Air.local" name="validOrderId" tests="1" failures="1" timestamp="21 Nov 2019 06:56:40 GMT" time="31.029" errors="0">
  <testcase name="testGetOrdersById" time="6.427" classname="in.shark.online.web.test.outlet.TestGetOrderByIdApiTestNg">
    <failure type="java.lang.AssertionError" message="Status expected:&amp;lt;200 OK&amp;gt; but was:&amp;lt;404 NOT_FOUND&amp;gt;

&amp;gt; GET https://qa3-api.chaipoint.com/outlet-pos-api/api/order/id?orderId=CH4374700000002
&amp;gt; WebTestClient-Request-Id: [1]
&amp;gt; Cookie: [app_cp=e7ab992f-b94e-4017-95bd-a5dabb917698]
&amp;gt; service.auth.key: [1234567]
&amp;gt; content-type: [application/json;charset=UTF-8]

No content

&amp;lt; 404 NOT_FOUND Not Found
&amp;lt; Date: [Thu, 21 Nov 2019 06:56:33 GMT]
&amp;lt; Content-Type: [application/json;charset=UTF-8]
&amp;lt; Transfer-Encoding: [chunked]
&amp;lt; Connection: [keep-alive]
&amp;lt; Server: [Apache-Coyote/1.1]
&amp;lt; X-Content-Type-Options: [nosniff]
&amp;lt; X-XSS-Protection: [1; mode=block]
&amp;lt; Cache-Control: [no-cache, no-store, max-age=0, must-revalidate]
&amp;lt; Pragma: [no-cache]
&amp;lt; Expires: [0]
&amp;lt; X-Frame-Options: [DENY]
&amp;lt; Access-Control-Allow-Headers: [Content-Type, Cookie, service.auth.key]
&amp;lt; Access-Control-Allow-Credentials: [true]
&amp;lt; Access-Control-Max-Age: [86400]

{&amp;quot;timestamp&amp;quot;:1574319393639,&amp;quot;status&amp;quot;:404,&amp;quot;error&amp;quot;:&amp;quot;Not Found&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;No handler found for GET /outlet-pos-api/api/order/id&amp;quot;,&amp;quot;path&amp;quot;:&amp;quot;/outlet-pos-api/api/order/id&amp;quot;}
">
      <![CDATA[java.lang.AssertionError: Status expected:<200 OK> but was:<404 NOT_FOUND>

> GET https://qa3-api.chaipoint.com/outlet-pos-api/api/order/id?orderId=CH4374700000002
> WebTestClient-Request-Id: [1]
> Cookie: [app_cp=e7ab992f-b94e-4017-95bd-a5dabb917698]
> service.auth.key: [1234567]
> content-type: [application/json;charset=UTF-8]

No content

< 404 NOT_FOUND Not Found
< Date: [Thu, 21 Nov 2019 06:56:33 GMT]
< Content-Type: [application/json;charset=UTF-8]
< Transfer-Encoding: [chunked]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< X-Content-Type-Options: [nosniff]
< X-XSS-Protection: [1; mode=block]
< Cache-Control: [no-cache, no-store, max-age=0, must-revalidate]
< Pragma: [no-cache]
< Expires: [0]
< X-Frame-Options: [DENY]
< Access-Control-Allow-Headers: [Content-Type, Cookie, service.auth.key]
< Access-Control-Allow-Credentials: [true]
< Access-Control-Max-Age: [86400]

{"timestamp":1574319393639,"status":404,"error":"Not Found","message":"No handler found for GET /outlet-pos-api/api/order/id","path":"/outlet-pos-api/api/order/id"}

	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:200)
	at org.springframework.test.web.reactive.server.StatusAssertions.assertStatusAndReturn(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.StatusAssertions.isOk(StatusAssertions.java:67)
	at in.shark.online.web.test.outlet.TestGetOrderByIdApiTestNg.testGetOrdersById(TestGetOrderByIdApiTestNg.java:51)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
Caused by: java.lang.AssertionError: Status expected:<200 OK> but was:<404 NOT_FOUND>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
	at org.springframework.test.web.reactive.server.StatusAssertions.lambda$assertStatusAndReturn$4(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:197)
	... 34 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGetOrdersById -->
</testsuite> <!-- validOrderId -->
