<html>
<head>
<title>TestNG:  invalidDatatypeTimestamp</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>invalidDatatypeTimestamp</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>0/1/0</td>
</tr><tr>
<td>Started on:</td><td>Wed Dec 04 15:56:09 IST 2019</td>
</tr>
<tr><td>Total time:</td><td>0 seconds (97 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode()'><b>testErrorCode</b><br>Test class: cool.fountain.online.web.test.errors.TestErrorsForPostReq<br>Parameters: 1234567, /api/event/heartbeat, test-files/json-data/event-master/heartbeat/invalidDatatypeTimestamp.json, INVALID_TERMINAL_ID</td>
<td><div><pre>java.lang.AssertionError: Status expected:&lt;400 BAD_REQUEST&gt; but was:&lt;200 OK&gt;

&gt; POST https://qa3-api.chaipoint.com/outlet-pos-api/api/event/heartbeat
&gt; Content-Length: [54]
&gt; WebTestClient-Request-Id: [1]
&gt; service.auth.key: [1234567]
&gt; Content-Type: [application/json]

{
  &quot;terminalId&quot;: &quot;terminal_1&quot;,
  &quot;timestamp&quot;: 12.34
}

&lt; 200 OK OK
&lt; Date: [Wed, 04 Dec 2019 10:26:10 GMT]
&lt; Content-Type: [application/json;charset=UTF-8]
&lt; Transfer-Encoding: [chunked]
&lt; Connection: [keep-alive]
&lt; Server: [Apache-Coyote/1.1]
&lt; Access-Control-Allow-Headers: [Content-Type, Cookie, service.auth.key]
&lt; Access-Control-Allow-Credentials: [true]
&lt; Access-Control-Max-Age: [86400]
&lt; X-Content-Type-Options: [nosniff]
&lt; X-XSS-Protection: [1; mode=block]
&lt; Cache-Control: [no-cache, no-store, max-age=0, must-revalidate]
&lt; Pragma: [no-cache]
&lt; Expires: [0]
&lt; X-Frame-Options: [DENY]

true

	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:200)
	at org.springframework.test.web.reactive.server.StatusAssertions.assertStatusAndReturn(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.StatusAssertions.isBadRequest(StatusAssertions.java:131)
	at cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(TestErrorsForPostReq.java:61)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
Caused by: java.lang.AssertionError: Status expected:&lt;400 BAD_REQUEST&gt; but was:&lt;200 OK&gt;
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
	at org.springframework.test.web.reactive.server.StatusAssertions.lambda$assertStatusAndReturn$4(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:197)
	... 34 more
... Removed 30 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace522082506", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace522082506'><pre>java.lang.AssertionError: Status expected:&lt;400 BAD_REQUEST&gt; but was:&lt;200 OK&gt;

&gt; POST https://qa3-api.chaipoint.com/outlet-pos-api/api/event/heartbeat
&gt; Content-Length: [54]
&gt; WebTestClient-Request-Id: [1]
&gt; service.auth.key: [1234567]
&gt; Content-Type: [application/json]

{
  &quot;terminalId&quot;: &quot;terminal_1&quot;,
  &quot;timestamp&quot;: 12.34
}

&lt; 200 OK OK
&lt; Date: [Wed, 04 Dec 2019 10:26:10 GMT]
&lt; Content-Type: [application/json;charset=UTF-8]
&lt; Transfer-Encoding: [chunked]
&lt; Connection: [keep-alive]
&lt; Server: [Apache-Coyote/1.1]
&lt; Access-Control-Allow-Headers: [Content-Type, Cookie, service.auth.key]
&lt; Access-Control-Allow-Credentials: [true]
&lt; Access-Control-Max-Age: [86400]
&lt; X-Content-Type-Options: [nosniff]
&lt; X-XSS-Protection: [1; mode=block]
&lt; Cache-Control: [no-cache, no-store, max-age=0, must-revalidate]
&lt; Pragma: [no-cache]
&lt; Expires: [0]
&lt; X-Frame-Options: [DENY]

true

	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:200)
	at org.springframework.test.web.reactive.server.StatusAssertions.assertStatusAndReturn(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.StatusAssertions.isBadRequest(StatusAssertions.java:131)
	at cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(TestErrorsForPostReq.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:182)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:194)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Status expected:&lt;400 BAD_REQUEST&gt; but was:&lt;200 OK&gt;
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
	at org.springframework.test.web.reactive.server.StatusAssertions.lambda$assertStatusAndReturn$4(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:197)
	... 34 more
</pre></div></td>
<td>0</td>
<td>cool.fountain.online.web.test.errors.TestErrorsForPostReq@6497b078</td></tr>
</table><p>
</body>
</html>