<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Chaipoints-MacBook-Air.local" name="terminalIdBoundaryCheck" tests="1" failures="1" timestamp="3 Dec 2019 08:28:26 GMT" time="0.12" errors="0">
  <testcase name="testBadRequest" time="0.113" classname="cool.fountain.online.web.test.errors.TestErrorsForPostReq">
    <failure type="java.lang.AssertionError" message="No value at JSON path &amp;quot;$.error&amp;quot;">
      <![CDATA[java.lang.AssertionError: No value at JSON path "$.error"
	at org.springframework.test.util.JsonPathExpectationsHelper.evaluateJsonPath(JsonPathExpectationsHelper.java:295)
	at org.springframework.test.util.JsonPathExpectationsHelper.assertValue(JsonPathExpectationsHelper.java:98)
	at org.springframework.test.web.reactive.server.JsonPathAssertions.isEqualTo(JsonPathAssertions.java:53)
	at cool.fountain.online.web.test.errors.TestErrorsForPostReq.testBadRequest(TestErrorsForPostReq.java:87)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
Caused by: com.jayway.jsonpath.PathNotFoundException: No results for path: $['error']
	at com.jayway.jsonpath.internal.path.EvaluationContextImpl.getValue(EvaluationContextImpl.java:133)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:345)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:329)
	at org.springframework.test.util.JsonPathExpectationsHelper.evaluateJsonPath(JsonPathExpectationsHelper.java:292)
	... 34 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testBadRequest -->
</testsuite> <!-- terminalIdBoundaryCheck -->
